### ISSUE TITLE
Help command showing color formatting instead of colored text

### ISSUE THREAD

**Issue by Mako88** [joshschmille/sate#9]
Using Windows Terminal with the Dracula theme, and SATE v0.9.1 the help command is displaying oddly:

![image](https://user-images.githubusercontent.com/4147635/123026465-d617a000-d3a1-11eb-8f6e-d888dd62641b.png)

Colors appear to be working fine in other commands though

Thanks for this awesome tool BTW!

**Comment by joshschmille** [comment]
Thanks for the bug report!

This has been fixed in the next update. Not exactly sure when that will be, but hopefully very soon.
